### ISSUE TITLE
安装后报错

### ISSUE THREAD

**Issue by mcyydscc** [Moxin1044/CTFd-gocqhttp-bot#1]
放入插件，修改CTFd/admin/_init_.py 后会有如下报错
```
ctfd_1   | Waiting for db to be ready
ctfd_1   | db is ready
ctfd_1   | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
ctfd_1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/opt/CTFd/manage.py", line 19, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 284, in create_app
ctfd_1   |     from CTFd.admin import admin
ctfd_1   |   File "/opt/CTFd/CTFd/admin/__init__.py", line 6
ctfd_1   |     from CTFd.Plugin.gocqhttpbot.gocq
ctfd_1   |                                      ^
ctfd_1   | SyntaxError: invalid syntax

```
![image](https://user-images.githubusercontent.com/90653809/230708103-18d8e123-3ebf-46c7-992f-a7afb79e113d.png)

**Comment by Moxin1044** [comment]
Plugin中将插件的Ctfd-gocqhttp-bot文件夹名称修改为gocqhttpbot即可。

**Comment by mcyydscc** [comment]
![image](https://user-images.githubusercontent.com/90653809/230709024-a51df7a9-f3ce-4a44-847f-308894306740.png)
原本的文件夹名称就是gocqhttpbot

**Comment by Moxin1044** [comment]
抱歉，是我README.md写错了，修改CTFd/admin/__init__.py，在头部引用我们的插件：

from CTFd.Plugins.gocq import xxx
