### ISSUE TITLE
get_ip 函数未定义

### ISSUE THREAD

**Issue by mcyydscc** [Moxin1044/CTFd-gocqhttp-bot#2]
进入admin界面时，会500报错，查看日志发现是get_ip 这个函数没有定义，应该在哪里添加
```
ctfd_1   | ERROR [CTFd] Exception on /admin [GET]
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
ctfd_1   |     response = self.full_dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
ctfd_1   |     rv = self.handle_user_exception(e)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 672, in error_router
ctfd_1   |     return original_handler(e)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
ctfd_1   |     reraise(exc_type, exc_value, tb)
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
ctfd_1   |     raise value
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
ctfd_1   |     rv = self.dispatch_request()
ctfd_1   |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
ctfd_1   |     return self.view_functions[rule.endpoint](**req.view_args)
ctfd_1   |   File "/opt/CTFd/CTFd/admin/__init__.py", line 58, in view
ctfd_1   |     ip = get_ip(request)
ctfd_1   | NameError: name 'get_ip' is not defined
```

**Comment by Moxin1044** [comment]
检查你的/opt/CTFd/CTFd/admin/__init__.py文件里，有没有下面这段引用语句：
`from CTFd.utils.user import is_admin,get_ip`
如果没有，请加上！
